// Self-hosted home page images. Photos come in AVIF and WebP at several widths
// (generated by scripts/optimize-images.mjs); illustrations are SVG. Credits: CREDITS.md.
import heroDataflow from './hero-dataflow.svg'
import transactionFlow from './transaction-flow.svg'
import aiTutor from './ai-tutor.svg'

export const illustrations = { heroDataflow, transactionFlow, aiTutor }

export type PhotoName = 'platform' | 'support' | 'assessment' | 'analytics'

const files = import.meta.glob<string>('./*-{400,800,1200}.{avif,webp}', { eager: true, query: '?url', import: 'default' })
const WIDTHS = [400, 800, 1200]

export interface PhotoSources {
  avif: string
  webp: string
  fallback: string
}

export function photoSources(name: PhotoName): PhotoSources {
  const set = (ext: string) => WIDTHS.map((w) => `${files[`./${name}-${w}.${ext}`]} ${w}w`).join(', ')
  return { avif: set('avif'), webp: set('webp'), fallback: files[`./${name}-800.webp`] }
}
